title: <p align="center"> Sushant Verma </p>

logo: "/images/sushant.png?raw=true"

description: |
  <p align="center">
  Bengaluru, India
  <br> (+91) 8765365100
  <br> <a href="mailto:sushantv2v@live.com">sushantv2v@live.com</a>
  <br> <a href="https://www.linkedin.com/in/sushant-verma-248b16101/">LinkedIn</a> |
  <a href="https://github.com/sushantv2v">GitHub</a>
  </p>
  
  <p align="justify">
  Seasoned Data Scientist with over 6 years of experience specializing in leveraging Machine Learning algorithms to solve complex business challenges.
  <br><br>
  Adept in multiple industries including Multimedia, E-commerce, Hyperlocal, and Digital Analytics Services.
  </p>
  
theme: jekyll-theme-minimal
